name: app

# The toolstack used to build the application.
type: nodejs:6.9
build:
    flavor: none

dependencies:
  nodejs:
    yarn: "*"

# The size of the persistent disk of the application (in MB).
disk: 1024

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
      set -e
      yarn install
      npm run build
    deploy: |
      npm run buildenvvar
